sonar.projectKey=shaad4_21orange-url-shortener
sonar.organization=shaad4

sonar.sources=shortener-service,stats-service,qr-service,frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**,**/*.test.jsx,frontend/dist/**

sonar.tests=shortener-service,stats-service,qr-service,frontend/src
sonar.test.inclusions=**/tests.py,**/*.test.jsx

sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=shortener-service/coverage.xml,stats-service/coverage.xml,qr-service/coverage.xml
sonar.exclusions=**/migrations/**,**/node_modules/**,**/*.test.jsx,frontend/dist/**,frontend/src/assets/**