apiVersion: apps/v1             # API version
kind: Deployment                # type of object
metadata:
  name: qr-service       # name of this Deployment object
spec:
  replicas: 1                   # how many Pod copies to keep running
  selector:
    matchLabels:
      app: qr-service    # Deployment manages any Pod with this label
  template:                     # this is the "Pod blueprint
    metadata:
      labels:
        app: qr-service  # the label being matched above
    spec:
      containers:
        - name: qr-service
          image: qr-service:v1
          imagePullPolicy: Never   # IMPORTANT: use the local image, don't try to pull from the internet
          ports:
            - containerPort: 8003
          env:
            - name: SHORTENER_SERVICE_URL
              value: "http://shortener-service:8001"
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://21orange.local"
            - name: QR_SECRET_KEY
              value: "django-insecure-q9u8i7y6-f)20(b%*h3_&^u-p*y6^z2+&x5z0s7f8f=6@+*3"