apiVersion: v1
kind: Service
metadata:
  name: qr-service           # this becomes the DNS name other Pods use
spec:
  selector:
    app: qr-service          # routes traffic to Pods with this label
  ports:
    - port: 8003                   # port the Service exposes internally
      targetPort: 8003              # port the container actually listens on