apiVersion: apps/v1             # API version
kind: Deployment                # type of object
metadata:
  name: stats-service           # name of this Deployment object
spec:
  replicas: 1                   # how many Pod copies to keep running
  selector:
    matchLabels:
      app: stats-service        # Deployment manages any Pod with this label
  template:                     # this is the "Pod blueprint
    metadata:
      labels:
        app: stats-service      # the label being matched above
    spec:
      containers:
        - name: stats-service
          image: stats-service:v1
          imagePullPolicy: Never   # IMPORTANT: use the local image, don't try to pull from the internet
          command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"]
          ports:
            - containerPort: 8002
          env:
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://21orange.local"
            - name: STATS_SECRET_KEY
              value: "django-insecure-k3j4n6l5-f)20(b%*h3_&^u-p*y6^z2+&x5z0s7f8f=6@+*2"
          