# Generated by Django 5.0.14 on 2026-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=6)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
